from langchain_neo4j import Neo4jVector
from langchain_neo4j.vectorstores.neo4j_vector import SearchType

from core.database import get_neo4j_graph
from core.config import settings
from core.llm import get_embeddings

class HybridRetrieverService:
    def __init__(self):
        self.graph = get_neo4j_graph()
        self.embeddings = get_embeddings()
        self.vector_index = self._initialize_vector_store()

    def _initialize_vector_store(self):
        """
        Creates or binds to the Neo4j Vector index on the Product node.
        This provides the anchor for our subsequent multi-hop traversals.
        """
        if not self.graph:
            return None

        print("Binding Hybrid Vector Index for Enterprise Retrieval...")

        # The hybrid retrieval query defines what happens AFTER the vector search finds the closest Product anchor nodes.
        # `node` is the implicitly matched Product vector anchor.
        # We bounce out 1-hop or 2-hops to pull associated knowledge.
        retrieval_query = """
        OPTIONAL MATCH (node)-[r]->(neighbor)
        WITH node, score, collect({relation: type(r), neighbor: neighbor.id, type: labels(neighbor)[0]}) as knowledge_edges
        
        OPTIONAL MATCH (node)<-[:ABOUT]-(rev:Review)<-[:WROTE]-(c:Customer)
        WITH node, score, knowledge_edges, collect({rating: rev.rating, comment: rev.comment, customer_city: c.city})[0..5] as verified_sentiments
        
        RETURN 'Product: ' + coalesce(node.title, node.id) + '\\nPrice: $' + toString(coalesce(node.price, 0)) + '\\nCategory: ' + coalesce(node.category, '') + '\\nImageURL: ' + coalesce(node.image, '') + '\\nDescription: ' + coalesce(node.description, '') + '\\nCustomer Sentiments: ' + coalesce(reduce(s = '', item IN verified_sentiments | s + (CASE WHEN item.rating IS NOT NULL THEN '[' + toString(item.rating) + '* from ' + coalesce(item.customer_city, 'Unknown') + ': ' + coalesce(item.comment, 'No comment') + '] ' ELSE '' END)), 'None') AS text,
               score,
               {
                   id: node.id,
                   price: node.price,
                   image: node.image,
                   associated_knowledge: knowledge_edges,
                   verified_sentiments: verified_sentiments
               } AS metadata
        """

        # We connect instantaneously to the pre-built indexes compiled by our ETL pipeline.
        return Neo4jVector.from_existing_index(
            embedding=self.embeddings,
            url=settings.NEO4J_URI,
            username=settings.NEO4J_USERNAME,
            password=settings.NEO4J_PASSWORD,
            index_name="product_hybrid_index",
            keyword_index_name="product_keyword_index",
            node_label="Product",
            text_node_property="title",
            embedding_node_property="embedding",
            retrieval_query=retrieval_query,
            search_type=SearchType.HYBRID,
        )

    def get_multi_hop_retriever(self):
        """
        Returns a customized LangChain retriever that combines vector similarity
        search with Cypher-based multi-hop traversal to enrich the context
        with associated nodes (e.g. Benefits, Features).
        """
        if not self.vector_index:
            return None

        # Configure search constraints
        return self.vector_index.as_retriever(
            search_kwargs={
                "k": 1000, # Retrieve top 1000 Hybrid nodes to allow adequate variance after deduplication (overcomes 150 variants per product generated by ETL)
            }
        )

# Singleton export
hybrid_retriever_service = HybridRetrieverService()
